### ISSUE TITLE
Crash on clarity-wasm-next

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-core#4215]
**Describe the bug**
When running [this commit](https://github.com/stacks-network/stacks-core/commit/c8db64c59ad9d95b53dbc37d529da4b43043fac3) from the `clarity-wasm-next` branch, the stacks node crashes when booting using a Bitcoin node in regtest mode from an empty state.
The crash emits a stack trace, but strangely no error leading up to it

```
2023-12-26T10:20:51-05:00	Dumping core for pid 1
2023-12-26T10:20:51-05:00	Panic backtrace:    0: stacks_node::main::{{closure}}
             at build/testnet/stacks-node/src/main.rs:54:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   5: core::panicking::panic_fmt
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   7: core::result::Result<T,E>::expect
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1034:23
      stacks_node::monitoring::prometheus::start_serving_prometheus_metrics::{{closure}}
             at build/testnet/stacks-node/src/monitoring/prometheus.rs:11:24
      <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/builder.rs:199:17
      async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
      std::thread::local::LocalKey<T>::try_with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
      async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:17
      <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/builder.rs:197:13
   8: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:446:33
   9: async_executor::Executor::run::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
      async_executor::LocalExecutor::run::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:480:34
      async_io::driver::block_on::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-io-2.2.2/src/driver.rs:199:37
      std::thread::local::LocalKey<T>::try_with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
      async_io::driver::block_on
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-io-2.2.2/src/driver.rs:175:11
  10: async_global_executor::reactor::block_on::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/reactor.rs:3:18
      async_global_executor::reactor::block_on
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/reactor.rs:12:5
      async_global_executor::executor::block_on::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/executor.rs:26:36
      std::thread::local::LocalKey<T>::try_with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
      async_global_executor::executor::block_on
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-global-executor-2.4.1/src/executor.rs:26:20
  11: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/builder.rs:171:25
      async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
      std::thread::local::LocalKey<T>::try_with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
      async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:17
      async_std::task::builder::Builder::blocking::{{closure}}
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/builder.rs:168:17
      std::thread::local::LocalKey<T>::try_with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
      async_std::task::builder::Builder::blocking
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/builder.rs:161:29
  12: async_std::task::block_on::block_on
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-std-1.12.0/src/task/block_on.rs:33:5
      stacks_node::monitoring::prometheus::start_serving_prometheus_metrics
             at build/testnet/stacks-node/src/monitoring/prometheus.rs:10:5
      stacks_node::monitoring::start_serving_monitoring_metrics
             at build/testnet/stacks-node/src/monitoring/mod.rs:11:5
  13: stacks_node::run_loop::nakamoto::RunLoop::start_prometheus::{{closure}}
             at build/testnet/stacks-node/src/run_loop/nakamoto.rs:342:21
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
      std::panicking::try
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  16: <unknown>
  17: <unknown>

2023-12-26T10:20:50-05:00	Relayer: handling directive
2023-12-26T10:20:50-05:00	Handle StacksHttpRequest
2023-12-26T10:20:50-05:00	Relayer: handling directive
2023-12-26T10:20:50-05:00	Relayer: Process sortition
2023-12-26T10:20:50-05:00	Runloop: Synchronized full burnchain up to height 124. Proceeding to mine blocks
2023-12-26T10:20:50-05:00	Relayer: handling directive
2023-12-26T10:20:50-05:00	Tenure: Notify burn block!
2023-12-26T10:20:50-05:00	Received burnchain block #124 including block_commit_op (winning) - miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT (f5e43aee1e9b3b67d6e9859255d8855b4e6067b5d2fc29c37f32339cedb1f661)
2023-12-26T10:20:50-05:00	Relayer: Process sortition
2023-12-26T10:20:50-05:00	Relayer: handling directive
2023-12-26T10:20:50-05:00	Tenure: Notify burn block!
2023-12-26T10:20:50-05:00	Received burnchain block #123 including block_commit_op (winning) - miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT (d0690ede15b488ab4e760be46507d33d4a3303b4ddb8c8d1a3a0d838371927d1)
2023-12-26T10:20:50-05:00	Relayer: Process sortition
2023-12-26T10:20:50-05:00	Relayer: handling directive
2023-12-26T10:20:50-05:00	Tenure: Notify burn block!
2023-12-26T10:20:50-05:00	Received burnchain block #122 including block_commit_op (winning) - miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT (4adfbcdedef7e768d956e32279cd283b4d0bee506f4877c42b006eadd1e3c2f8)
2023-12-26T10:20:50-05:00	Runloop: Downloaded burnchain blocks up to height 124; target height is 124; remote_chain_height = 124 next_sortition_height = 124, sortition_db_height = 121
2023-12-26T10:20:50-05:00	Start P2P server on: 0.0.0.0:20444
2023-12-26T10:20:50-05:00	Start HTTP server on: 0.0.0.0:20443
2023-12-26T10:20:50-05:00	Failed to set global burnchain signer: SetGlobalBurnchainSignerError
2023-12-26T10:20:50-05:00	Without a peer to bootstrap from, the node will start mining a new chain
2023-12-26T10:20:50-05:00	Process abort due to thread panic: panicked at testnet/stacks-node/src/monitoring/prometheus.rs:13:14:
Prometheus monitoring: unable to bind address: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
2023-12-26T10:20:50-05:00	Start serving prometheus metrics
2023-12-26T10:20:50-05:00	UTXOs found - will run as a Miner node
2023-12-26T10:20:50-05:00	Miner node: checking UTXOs at address: miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT
2023-12-26T10:20:50-05:00	Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
2023-12-26T10:20:50-05:00	Migrating chainstate DB to the latest schema version
2023-12-26T10:20:50-05:00	Migrating sortition DB to the latest schema version
2023-12-26T10:20:50-05:00	Error setting up signal handler, may have already been set
2023-12-26T10:20:50-05:00	Registering event observer at: regtest-api-nakamoto-2.regtest-api.svc.cluster.local:3700
2023-12-26T10:20:50-05:00	Reached Epoch-3.0 boundary, starting nakamoto node
```

**Steps To Reproduce**
Run the `clarity-wasm-next` branch in a regtest environment. You can do so by cloning the [regtest project](https://github.com/hirosystems/stacks-regtest-env/tree/epoch3-interim-blocks) (epoch3-interim-blocks branch) and modifying [this variable](https://github.com/hirosystems/stacks-regtest-env/blob/epoch3-interim-blocks/docker-compose.yml#L4C26-L4C26) to the `clarity-wasm-next` branch.

**Comment by CharlieC3** [comment]
FYI @obycode

**Comment by obycode** [comment]
I'm looking at this now. It looks to be another prometheus-related issue. There shouldn't be anything related to prometheus that is different in the `feat/clarity-wasm-next` branch.

What do I need to run after modifying that variable to reproduce this?

**Comment by CharlieC3** [comment]
@obycode I believe just `docker compose up`. I haven't tried replicating it via docker compose, but it's a very similar setup to what Hiro is running for the Neon node.
Also, you'll need to set this property in the [config toml file](https://github.com/hirosystems/stacks-regtest-env/blob/epoch3-interim-blocks/stacks-krypton-miner.toml) first as well.

```
[node]
...
prometheus_bind = "0.0.0.0:9153"
```

**Comment by csgui** [comment]
This issue can be closed, as clarity-wasm validations are now performed against the `feat/clarity-wasm-develop` branch. Additionally, the clarity-wasm team has begun validating changes against a node synced from genesis, and any issues will be reported accordingly.
