### ISSUE TITLE
BUG: no genesis header log in wasm miner

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-core#4297]
When running the `test-always-wasm` branch as a mocker miner on mainnet, it frequently crashes with the following error:

```
{"msg":"Miner node: checking UTXOs at address: 1PfUdeniBzz6378rSTVyVa3i5aSw3SmmgH","level":"INFO","ts":"2024-01-26T04:20:08.882862451Z","thread":"main","line":367,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
{"msg":"UTXOs not found for 1PfUdeniBzz6378rSTVyVa3i5aSw3SmmgH. If this is unexpected, please ensure that your bitcoind instance is indexing transactions for the address 1PfUdeniBzz6378rSTVyVa3i5aSw3SmmgH (importaddress)","level":"WARN","ts":"2024-01-26T04:20:08.88293041Z","thread":"main","line":370,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
{"msg":"No UTXOs found, but configured to mock mine","level":"INFO","ts":"2024-01-26T04:20:08.882966116Z","thread":"main","line":377,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
{"msg":"Self-signing is not supported yet","level":"WARN","ts":"2024-01-26T04:20:08.886446639Z","thread":"main","line":493,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
{"msg":"Migrated MARF data to schema 2","level":"DEBG","ts":"2024-01-26T04:20:08.887291986Z","thread":"main","line":153,"file":"/usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/index/trie_sql.rs"}
{"msg":"Opened TrieFileStorage /hirosystems/data/mainnet/chainstate/vm/index.sqlite; external blobs: true","level":"DEBG","ts":"2024-01-26T04:20:08.887378867Z","thread":"main","line":1442,"file":"/usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/index/storage.rs"}
{"msg":"Migrated MARF data to schema 2","level":"DEBG","ts":"2024-01-26T04:20:08.887899372Z","thread":"main","line":153,"file":"/usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/index/trie_sql.rs"}
{"msg":"Opened TrieFileStorage /hirosystems/data/mainnet/chainstate/vm/clarity/marf.sqlite; external blobs: true","level":"DEBG","ts":"2024-01-26T04:20:08.887981078Z","thread":"main","line":1442,"file":"/usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/index/storage.rs"}
{"msg":"Process abort due to thread panic: panicked at /usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/db/headers.rs:324:20:\nBUG: no genesis header info","level":"ERRO","ts":"2024-01-26T04:20:08.88815143Z","thread":"main","line":53,"file":"testnet/stacks-node/src/main.rs"}
{"msg":"Panic backtrace:    0: stacks_node::main::{{closure}}\n             at build/testnet/stacks-node/src/main.rs:54:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9\n      std::panicking::rust_panic_with_hook\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18\n   4: rust_begin_unwind\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5\n   5: core::panicking::panic_fmt\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14\n   6: core::panicking::panic_display\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:178:5\n      core::panicking::panic_str\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:152:5\n      core::option::expect_failed\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:1985:5\n   7: core::option::Option<T>::expect\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:894:21\n      blockstack_lib::chainstate::stacks::db::headers::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::get_genesis_header_info\n             at usr/local/cargo/git/checkouts/stacks-core-2fc446cf3f61ae17/52f26b2/stackslib/src/chainstate/stacks/db/headers.rs:324:20\n   8: stacks_node::run_loop::announce_boot_receipts\n             at build/testnet/stacks-node/src/run_loop/mod.rs:169:26\n   9: stacks_node::run_loop::neon::RunLoop::boot_chainstate\n             at build/testnet/stacks-node/src/run_loop/neon.rs:525:9\n      stacks_node::run_loop::neon::RunLoop::spawn_chains_coordinator\n             at build/testnet/stacks-node/src/run_loop/neon.rs:554:30\n      stacks_node::run_loop::neon::RunLoop::start\n             at build/testnet/stacks-node/src/run_loop/neon.rs:1037:41\n  10: stacks_node::main\n             at build/testnet/stacks-node/src/main.rs:211:9\n  11: core::ops::function::FnOnce::call_once\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18\n  12: std::rt::lang_start::{{closure}}\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18\n  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13\n      std::panicking::try::do_call\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40\n      std::panicking::try\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19\n      std::panic::catch_unwind\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14\n      std::rt::lang_start_internal::{{closure}}\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48\n      std::panicking::try::do_call\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40\n      std::panicking::try\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19\n      std::panic::catch_unwind\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14\n      std::rt::lang_start_internal\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20\n  14: std::rt::lang_start\n             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17\n  15: <unknown>\n  16: __libc_start_main\n  17: _start\n","level":"ERRO","ts":"2024-01-26T04:20:09.177864461Z","thread":"main","line":55,"file":"testnet/stacks-node/src/main.rs"}
Dumping core for pid 1
Stream closed EOF for mainnet-stacks/mainnet-wasm-miner-0 (stacks-blockchain)
```

**Comment by csgui** [comment]
This needs to be validated on a node synced from genesis and running the latest clarity-wasm changes. There's a [task](https://github.com/stacks-network/clarity-wasm/issues/637) in the clarity-wasm project that can also be used to check this issue. I'm assigning it to myself and will provide an update here as soon as I have results from that task.
