### ISSUE TITLE
Nakamoto-1: unknown PoX anchor block in Nakamoto

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-core#4341]
Nakamoto-1 (existing Clarity VM) is crashlooping at Stacks block `240351` due to the error, `unknown PoX anchor block in Nakamoto`.
The events which caused this is not known.

Relevant logs:

```
{"msg":"stacks-node 70f7b7d (nakamoto-v0.3:70f7b7d, release build, linux [x86_64])","level":"INFO","ts":"2024-02-05T14:40:54.464823832Z","thread":"main","line":76,"file":"testnet/stacks-node/src/main.rs"}
{"msg":"Loading config at path /app/config.toml","level":"INFO","ts":"2024-02-05T14:40:54.464877126Z","thread":"main","line":138,"file":"testnet/stacks-node/src/main.rs"}
{"msg":"Registering event observer at: regtest-api-nakamoto-1.regtest-api.svc.cluster.local:3700","level":"INFO","ts":"2024-02-05T14:40:54.468428152Z","thread":"main","line":1081,"file":"testnet/stacks-node/src/event_dispatcher.rs"}
{"msg":"Migrating sortition DB to the latest schema version","level":"INFO","ts":"2024-02-05T14:40:54.472290494Z","thread":"main","line":3389,"file":"stackslib/src/chainstate/coordinator/mod.rs"}
{"msg":"Migrating chainstate DB to the latest schema version","level":"INFO","ts":"2024-02-05T14:40:54.473127194Z","thread":"main","line":3393,"file":"stackslib/src/chainstate/coordinator/mod.rs"}
{"msg":"Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while","level":"INFO","ts":"2024-02-05T14:40:54.476322844Z","thread":"main","line":428,"file":"testnet/stacks-node/src/run_loop/neon.rs"}
{"msg":"New canonical Bitcoin chain found! New tip is 6e351a9fd0252ff9f36bbd3c42d41c3ffd1b0213143c5c9507cac810eecbb6db","level":"INFO","ts":"2024-02-05T14:40:54.590661601Z","thread":"main","line":805,"file":"stackslib/src/burnchains/bitcoin/indexer.rs"}
{"msg":"Syncing Bitcoin blocks: 100.0% (3010 to 3011 out of 3010)","level":"INFO","ts":"2024-02-05T14:40:54.610307374Z","thread":"main","line":1476,"file":"stackslib/src/burnchains/burnchain.rs"}
{"msg":"Miner node: checking UTXOs at address: miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT","level":"INFO","ts":"2024-02-05T14:40:54.629180529Z","thread":"main","line":186,"file":"testnet/stacks-node/src/run_loop/nakamoto.rs"}
{"msg":"UTXOs found - will run as a Miner node","level":"INFO","ts":"2024-02-05T14:40:54.696838165Z","thread":"main","line":191,"file":"testnet/stacks-node/src/run_loop/nakamoto.rs"}
{"msg":"Start serving prometheus metrics","level":"INFO","ts":"2024-02-05T14:40:54.727734208Z","thread":"prometheus","line":9,"file":"testnet/stacks-node/src/monitoring/mod.rs"}
{"msg":"Prometheus monitoring: server listening on http://0.0.0.0:9153","level":"INFO","ts":"2024-02-05T14:40:54.727911429Z","thread":"prometheus","line":20,"file":"testnet/stacks-node/src/monitoring/prometheus.rs"}
{"msg":"Process burn block 2981 reward cycle 298 in /hirosystems/data/nakamoto-neon/burnchain","level":"INFO","ts":"2024-02-05T14:40:54.736242596Z","thread":"chains-coordinator-0.0.0.0:20443","line":741,"file":"stackslib/src/chainstate/nakamoto/coordinator/mod.rs","is_prior_in_prepare_phase":true,"is_rc_start":true,"in_prepare_phase":false}
{"msg":"Process abort due to thread panic: panicked at /build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:784:21:\nFATAL: unknown PoX anchor block in Nakamoto","level":"ERRO","ts":"2024-02-05T14:40:54.736994813Z","thread":"chains-coordinator-0.0.0.0:20443","line":53,"file":"testnet/stacks-node/src/main.rs"}
{"msg":"Without a peer to bootstrap from, the node will start mining a new chain","level":"WARN","ts":"2024-02-05T14:40:54.750235159Z","thread":"main","line":3689,"file":"testnet/stacks-node/src/neon_node.rs"}
{"msg":"Start HTTP server on: 0.0.0.0:20443","level":"INFO","ts":"2024-02-05T14:40:54.769498011Z","thread":"main","line":204,"file":"testnet/stacks-node/src/nakamoto_node.rs"}
{"msg":"Start P2P server on: 0.0.0.0:20444","level":"INFO","ts":"2024-02-05T14:40:54.769549946Z","thread":"main","line":205,"file":"testnet/stacks-node/src/nakamoto_node.rs"}
{"msg":"Panic backtrace:    0: stacks_node::main::{{closure}}\n             at build/testnet/stacks-node/src/main.rs:54:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9\n      std::panicking::rust_panic_with_hook\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18\n   4: rust_begin_unwind\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5\n   5: core::panicking::panic_fmt\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14\n   6: blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::handle_new_nakamoto_burnchain_block\n             at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:784:21\n   7: blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::handle_comms_nakamoto\n             at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:452:19\n      blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider,CE,FE,B>::run\n             at build/stackslib/src/chainstate/coordinator/mod.rs:481:21\n   8: stacks_node::run_loop::nakamoto::RunLoop::spawn_chains_coordinator::{{closure}}\n             at build/testnet/stacks-node/src/run_loop/nakamoto.rs:315:17\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18\n   9: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40\n      std::panicking::try\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19\n      std::panic::catch_unwind\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5\n  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17\n  11: <unknown>\n  12: <unknown>\n","level":"ERRO","ts":"2024-02-05T14:40:54.921270969Z","thread":"chains-coordinator-0.0.0.0:20443","line":55,"file":"testnet/stacks-node/src/main.rs"}
```

**Comment by obycode** [comment]
Do you know which commit this image is based on?

**Comment by CharlieC3** [comment]
@obycode I believe it's `nakamoto-v0.3:70f7b7d` (reference: https://api.nakamoto-1.hiro.so/v2/info), and it doesn't seem anyone has deployed to this env for about 2 weeks.
