### ISSUE TITLE
Crash when network connectivity lost

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/stacks-core#4423]
This doesn't happen every time the network connection is lost, but tonight when I was syncing a `next` node to mainnet using my phone's wifi hotspot and went out of range, the following crash occurred.

Low prio ticket, just documenting that it happened.

```
INFO [1708706569.491401] [stackslib/src/chainstate/stacks/db/transactions.rs:678] [chains-coordinator-0.0.0.0:20443] Post-condition check failure on non-fungible asset SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.citadels::citadels owned by SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-art-market-v2: UInt(2091) Sent
INFO [1708706569.491417] [stackslib/src/chainstate/stacks/db/transactions.rs:1063] [chains-coordinator-0.0.0.0:20443] Contract-call aborted by post-condition, contract_name: SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-art-market-v2, function_name: buy-item, function_args: [SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.citadels, u9, u2091]
ERRO [1708706575.556707] [testnet/stacks-node/src/main.rs:268] [chain-liveness-0.0.0.0:20443] Process abort due to thread panic: panicked at testnet/stacks-node/src/config.rs:1916:51:
called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }
ERRO [1708706575.950600] [testnet/stacks-node/src/main.rs:270] [chain-liveness-0.0.0.0:20443] Panic backtrace:    0: stacks_node::main::{{closure}}
             at src/main.rs:269:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   5: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   7: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
      stacks_node::config::NodeConfig::add_bootstrap_node
             at src/config.rs:1916:24
      stacks_node::config::NodeConfig::set_bootstrap_nodes
             at src/config.rs:1930:17
   8: stacks_node::config::Config::from_config_default
             at src/config.rs:936:13
   9: stacks_node::config::Config::from_config_file
             at src/config.rs:880:13
  10: stacks_node::config::Config::get_miner_config
             at src/config.rs:540:26
  11: stacks_node::run_loop::neon::RunLoop::drive_pox_reorg_stacks_block_processing
             at src/run_loop/neon.rs:680:28
      stacks_node::run_loop::neon::RunLoop::drive_chain_liveness
             at src/run_loop/neon.rs:956:13
  12: stacks_node::run_loop::neon::RunLoop::spawn_chain_liveness_thread::{{closure}}
             at src/run_loop/neon.rs:990:17
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
      std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
             at ./nptl/pthread_create.c:442:8
  16: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Dumping core for pid 2060764
Quit (core dumped)
```

**Comment by 8marz8** [comment]
@cylewitruk  Can I know which command to run? trying to reproduce the issue.

**Comment by cylewitruk** [comment]
> @cylewitruk  Can I know which command to run? trying to reproduce the issue.

This was simply a srarted node i.e. `./stacks-node start --config ..`.

**Comment by badonyx** [comment]
I am having the same problem and it has nothing to do with `Ctrl-C` handling. As far as I can tell this is not fixed.

**Comment by badonyx** [comment]
The problem is happening at
https://github.com/stacks-network/stacks-core/blob/9b377f9c36357d6bdc7df4134c0bfd358c42c651/testnet/stacks-node/src/config.rs#L1946

In the past this line would have only run at initialization, but now that the configuration file is getting read regularly this will immediately kill any node that encounters network connection issues.

**Comment by badonyx** [comment]
for reference the config change was made in #4250 @jcnelson

**Comment by cylewitruk** [comment]
Since this issue is already closed+merged I have added your find @badonyx in a new issue: #4585 . Good catch!
