### ISSUE TITLE
BUG: PeerNetwork could not bind or is already bound: BindError

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4531]
I ran into this panic today while running a full end-to-end local environment with regtest bitcoin + three signers. It was configured with a short pox cycle length (10 blocks), and fast bitcoin block mining times (5 seconds).

I haven't been able to reproduce the issue again, otherwise I'd include debug logs. For now, all I have is this segment of logs:

```
WARN [1710332960.799396] [testnet/stacks-node/src/neon_node.rs:4383] [main] Without a peer to bootstrap from, the node will start mining a new chain
ERRO [1710332960.811216] [stackslib/src/net/poll.rs:94] [main] Failed to bind to 0.0.0.0:20444: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
ERRO [1710332960.811280] [testnet/stacks-node/src/main.rs:270] [main] Process abort due to thread panic: panicked at testnet/stacks-node/src/nakamoto_node/peer.rs:186:14:
BUG: PeerNetwork could not bind or is already bound: BindError
INFO [1710332960.861608] [testnet/stacks-node/src/neon_node.rs:4285] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] P2P: Relayer hang up with p2p channel
INFO [1710332960.861641] [testnet/stacks-node/src/neon_node.rs:4639] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] P2P thread exit!
ERRO [1710332961.142966] [testnet/stacks-node/src/main.rs:272] [main] Panic backtrace:    0: stacks_node::main::{{closure}}
             at /stacks/testnet/stacks-node/src/main.rs:271:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   7: core::result::Result<T,E>::expect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
      stacks_node::nakamoto_node::peer::PeerThread::new_all
             at /stacks/testnet/stacks-node/src/nakamoto_node/peer.rs:185:9
      stacks_node::nakamoto_node::peer::PeerThread::new
             at /stacks/testnet/stacks-node/src/nakamoto_node/peer.rs:148:9
   8: stacks_node::nakamoto_node::StacksNode::spawn
             at /stacks/testnet/stacks-node/src/nakamoto_node.rs:193:26
   9: stacks_node::run_loop::nakamoto::RunLoop::start
             at /stacks/testnet/stacks-node/src/run_loop/nakamoto.rs:478:24
  10: stacks_node::run_loop::boot_nakamoto::BootRunLoop::start_from_neon
             at /stacks/testnet/stacks-node/src/run_loop/boot_nakamoto.rs:153:9
      stacks_node::run_loop::boot_nakamoto::BootRunLoop::start
             at /stacks/testnet/stacks-node/src/run_loop/boot_nakamoto.rs:102:45
  11: stacks_node::main
             at /stacks/testnet/stacks-node/src/main.rs:448:9
  12: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  13: std::rt::lang_start::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  15: main
  16: <unknown>
  17: __libc_start_main
  18: _start
```

**Comment by zone117x** [comment]
I'll update this issue with more information if I'm able to reproduce the bug. In the meantime it may be useful to check if there are address binding race conditions around `stackslib/src/net/poll.rs:94`

**Comment by jcnelson** [comment]
The address is already in use (see the messages above the panic). Not much
you can do about that besides change the config to use a different port or
kill whatever is using that port.

**Comment by zone117x** [comment]
It's possible I had a broken environment where that port was in use somehow, but I was running this like I normally have (hundreds of times so far). If we are absolutely 100% confident that there aren't any race conditions which could cause this, then feel free to close the issue, and I'll re-open if I see it again.

**Comment by jcnelson** [comment]
There are no race conditions. The peer binds early, before any threads are
started. Are you running this in an environment with other non-stacks
processes?

**Comment by zone117x** [comment]
These are run in an isolate docker-compose setup, so I'm not sure how the port could have been already in use within the container local network (it's possible some quirk in docker compose resetting kept some previous service alive, but I haven't ran into that before in this case).

**Comment by jcnelson** [comment]
Depending on the kernel details and configuration, you may be hitting a case where the underlying TCP socket from a prior run is still open but in a `TIME_WAIT` setting (see https://stackoverflow.com/questions/5106674/error-address-already-in-use-while-binding-socket-with-address-but-the-port-num). You'd be able to see with `lsof -P`.  It also would be intermittent.

**Comment by saralab** [comment]
Unable to recreate, closing for now
