### ISSUE TITLE
hash mismatch

### ISSUE THREAD

**Issue by rajeeja** [stacks-network/stacks-core#4613]
FATAL ERROR: name_zonefiles.txt hash mismatch, expected a7082d1ad4cfbc28820120531e02fa8b318110dae82ea98d8775ffaf9df945e6, got 48364929dd8be44312423d44c2cb3ba7507fcc05b2598580dcc0a97449f83615

on a windows machine

```
   Compiling clap_builder v4.4.1                                                                                         
error: failed to run custom build command for `stx-genesis v0.1.0 (C:\Users\rajee\stacks-core\stx-genesis)`              

Caused by:
  process didn't exit successfully: `C:\Users\rajee\stacks-core\target\debug\build\stx-genesis-376c61f2ed1c3310\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at stx-genesis\build.rs:184:9:
  FATAL ERROR: name_zonefiles.txt hash mismatch, expected a7082d1ad4cfbc28820120531e02fa8b318110dae82ea98d8775ffaf9df945e6, got 48364929dd8be44312423d44c2cb3ba7507fcc05b2598580dcc0a97449f83615
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
                                                                                                                         
rajee@jain MINGW64 ~/stacks-core (master)
$ cargo build
   Compiling serde_derive v1.0.156
   Compiling ctor v0.1.26
   Compiling futures-macro v0.3.28
   Compiling time-macros-impl v0.1.2
   Compiling thiserror-impl v1.0.39
   Compiling libsqlite3-sys v0.20.1
   Compiling rstest_macros v0.17.0
   Compiling rstest_reuse v0.5.0
   Compiling tracing-attributes v0.1.26
   Compiling async-attributes v1.1.2
   Compiling pin-project-internal v1.0.12
   Compiling addr2line v0.19.0
   Compiling clap_derive v4.4.0
   Compiling backtrace v0.3.67                                                                                           
   Compiling aes-gcm v0.10.2                                                                                             
   Compiling async-dup v1.2.2                                                                                            
   Compiling stx-genesis v0.1.0 (C:\Users\rajee\stacks-core\stx-genesis)                                                 
error: failed to run custom build command for `stx-genesis v0.1.0 (C:\Users\rajee\stacks-core\stx-genesis)`              

Caused by:
  process didn't exit successfully: `C:\Users\rajee\stacks-core\target\debug\build\stx-genesis-376c61f2ed1c3310\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at stx-genesis\build.rs:184:9:
  FATAL ERROR: name_zonefiles.txt hash mismatch, expected a7082d1ad4cfbc28820120531e02fa8b318110dae82ea98d8775ffaf9df945e6, got 48364929dd8be44312423d44c2cb3ba7507fcc05b2598580dcc0a97449f83615
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fdefelici** [comment]
@rajeeja I reproduced this issue and it should be due to a misconfiguration of autoclrf property of git.

By now, when developping on windows machine is highly suggested to set `core.autocrlf = input` (see [readme](https://github.com/stacks-network/stacks-core/blob/master/README.md#testing) at the Testing section)

After that, you should be able to compile without that error. 
Eventually if it is still persists, try to set the property and the clone the repository from scratch.

**Comment by fdefelici** [comment]
Mainly this issue affect the following packages/files:
- `stx-genesis`:  
  - `chainstate-test.txt`, `chainstate.txt`, `name_zonefiles-test.txt`, `name_zonefiles.txt`
  - during compilation
- `clarity`: 
  - basically all `.clar` files
  - during test execution
